version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Change to Correct Directory
          command: cd android
      - run:
          name: List the directory
          command: ls   
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run WebdriverIO Appium Tests on BrowserStack
          command: npm run test
workflows:
  version: 2
  build:
    jobs:
      - build
