version: 2.1

jobs:
  test:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Dependencies and Run Tests in Android Directory
          command: |
            cd android
            npm install
            npm run test

workflows:
  setup_and_test:
    jobs:
      - test:
          filters:
            branches:
              only:
                - master
