version: 2.1
jobs:
  test:
    machine: true
    filters:
      branches:
        only:
          - main
    steps:
      - checkout
      - run:
          name: Install Dependencies and Run Tests in Android Directory
          command: |
            cd android
            npm install
            npm run test
workflows:
  version: 2
  test_app:
    jobs:
      - test
